package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADMIN_CARD".
*/
public class AdminCardDao extends AbstractDao<AdminCard, String> {

    public static final String TABLENAME = "ADMIN_CARD";

    /**
     * Properties of entity AdminCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IsDel = new Property(0, Boolean.class, "isDel", false, "IS_DEL");
        public final static Property Card = new Property(1, String.class, "card", false, "CARD");
        public final static Property ObjectId = new Property(2, String.class, "objectId", true, "OBJECT_ID");
        public final static Property CreatedAt = new Property(3, String.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(4, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property Keepone = new Property(5, String.class, "keepone", false, "KEEPONE");
        public final static Property Keeptwo = new Property(6, String.class, "keeptwo", false, "KEEPTWO");
        public final static Property Keepthree = new Property(7, String.class, "keepthree", false, "KEEPTHREE");
    }


    public AdminCardDao(DaoConfig config) {
        super(config);
    }
    
    public AdminCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADMIN_CARD\" (" + //
                "\"IS_DEL\" INTEGER," + // 0: isDel
                "\"CARD\" TEXT NOT NULL ," + // 1: card
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 2: objectId
                "\"CREATED_AT\" TEXT," + // 3: createdAt
                "\"UPDATED_AT\" TEXT," + // 4: updatedAt
                "\"KEEPONE\" TEXT," + // 5: keepone
                "\"KEEPTWO\" TEXT," + // 6: keeptwo
                "\"KEEPTHREE\" TEXT);"); // 7: keepthree
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADMIN_CARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AdminCard entity) {
        stmt.clearBindings();
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(1, isDel ? 1L: 0L);
        }
        stmt.bindString(2, entity.getCard());
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(3, objectId);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(4, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(5, updatedAt);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(6, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(7, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(8, keepthree);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AdminCard entity) {
        stmt.clearBindings();
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(1, isDel ? 1L: 0L);
        }
        stmt.bindString(2, entity.getCard());
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(3, objectId);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(4, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(5, updatedAt);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(6, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(7, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(8, keepthree);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    @Override
    public AdminCard readEntity(Cursor cursor, int offset) {
        AdminCard entity = new AdminCard( //
            cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0, // isDel
            cursor.getString(offset + 1), // card
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // objectId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // createdAt
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // updatedAt
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // keepone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // keeptwo
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // keepthree
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AdminCard entity, int offset) {
        entity.setIsDel(cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0);
        entity.setCard(cursor.getString(offset + 1));
        entity.setObjectId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreatedAt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUpdatedAt(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setKeepone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setKeeptwo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setKeepthree(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(AdminCard entity, long rowId) {
        return entity.getObjectId();
    }
    
    @Override
    public String getKey(AdminCard entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AdminCard entity) {
        return entity.getObjectId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
