package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADMIN_CARD".
 */
@Entity
public class AdminCard {

    @Id
    private Long id;

    @NotNull
    private String card;
    private String objectId;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    @Generated
    public AdminCard() {
    }

    public AdminCard(Long id) {
        this.id = id;
    }

    @Generated
    public AdminCard(Long id, String card, String objectId, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.card = card;
        this.objectId = objectId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCard() {
        return card;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCard(@NotNull String card) {
        this.card = card;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
