package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BORROW_RECORD".
 */
@Entity
public class BorrowRecord implements Serializable {

    @Id
    private Long id;
    private Boolean isFlag;
    private String passage;
    private String card;
    private Boolean borrow;
    private Boolean result;
    private java.util.Date time;
    private String keepone;
    private String keeptwo;
    private String keepthree;

    @Generated
    public BorrowRecord() {
    }

    public BorrowRecord(Long id) {
        this.id = id;
    }

    @Generated
    public BorrowRecord(Long id, Boolean isFlag, String passage, String card, Boolean borrow, Boolean result, java.util.Date time, String keepone, String keeptwo, String keepthree) {
        this.id = id;
        this.isFlag = isFlag;
        this.passage = passage;
        this.card = card;
        this.borrow = borrow;
        this.result = result;
        this.time = time;
        this.keepone = keepone;
        this.keeptwo = keeptwo;
        this.keepthree = keepthree;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsFlag() {
        return isFlag;
    }

    public void setIsFlag(Boolean isFlag) {
        this.isFlag = isFlag;
    }

    public String getPassage() {
        return passage;
    }

    public void setPassage(String passage) {
        this.passage = passage;
    }

    public String getCard() {
        return card;
    }

    public void setCard(String card) {
        this.card = card;
    }

    public Boolean getBorrow() {
        return borrow;
    }

    public void setBorrow(Boolean borrow) {
        this.borrow = borrow;
    }

    public Boolean getResult() {
        return result;
    }

    public void setResult(Boolean result) {
        this.result = result;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getKeepone() {
        return keepone;
    }

    public void setKeepone(String keepone) {
        this.keepone = keepone;
    }

    public String getKeeptwo() {
        return keeptwo;
    }

    public void setKeeptwo(String keeptwo) {
        this.keeptwo = keeptwo;
    }

    public String getKeepthree() {
        return keepthree;
    }

    public void setKeepthree(String keepthree) {
        this.keepthree = keepthree;
    }

}
