package com.seekersoftvendingapp.database.table;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.seekersoftvendingapp.database.table.Note;
import com.seekersoftvendingapp.database.table.AdminCard;
import com.seekersoftvendingapp.database.table.Employee;
import com.seekersoftvendingapp.database.table.EmpPower;
import com.seekersoftvendingapp.database.table.Passage;
import com.seekersoftvendingapp.database.table.Product;

import com.seekersoftvendingapp.database.table.NoteDao;
import com.seekersoftvendingapp.database.table.AdminCardDao;
import com.seekersoftvendingapp.database.table.EmployeeDao;
import com.seekersoftvendingapp.database.table.EmpPowerDao;
import com.seekersoftvendingapp.database.table.PassageDao;
import com.seekersoftvendingapp.database.table.ProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig adminCardDaoConfig;
    private final DaoConfig employeeDaoConfig;
    private final DaoConfig empPowerDaoConfig;
    private final DaoConfig passageDaoConfig;
    private final DaoConfig productDaoConfig;

    private final NoteDao noteDao;
    private final AdminCardDao adminCardDao;
    private final EmployeeDao employeeDao;
    private final EmpPowerDao empPowerDao;
    private final PassageDao passageDao;
    private final ProductDao productDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        adminCardDaoConfig = daoConfigMap.get(AdminCardDao.class).clone();
        adminCardDaoConfig.initIdentityScope(type);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        empPowerDaoConfig = daoConfigMap.get(EmpPowerDao.class).clone();
        empPowerDaoConfig.initIdentityScope(type);

        passageDaoConfig = daoConfigMap.get(PassageDao.class).clone();
        passageDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        adminCardDao = new AdminCardDao(adminCardDaoConfig, this);
        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        empPowerDao = new EmpPowerDao(empPowerDaoConfig, this);
        passageDao = new PassageDao(passageDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(AdminCard.class, adminCardDao);
        registerDao(Employee.class, employeeDao);
        registerDao(EmpPower.class, empPowerDao);
        registerDao(Passage.class, passageDao);
        registerDao(Product.class, productDao);
    }
    
    public void clear() {
        noteDaoConfig.clearIdentityScope();
        adminCardDaoConfig.clearIdentityScope();
        employeeDaoConfig.clearIdentityScope();
        empPowerDaoConfig.clearIdentityScope();
        passageDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public AdminCardDao getAdminCardDao() {
        return adminCardDao;
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public EmpPowerDao getEmpPowerDao() {
        return empPowerDao;
    }

    public PassageDao getPassageDao() {
        return passageDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

}
