package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMP_POWER".
*/
public class EmpPowerDao extends AbstractDao<EmpPower, Long> {

    public static final String TABLENAME = "EMP_POWER";

    /**
     * Properties of entity EmpPower.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Unit = new Property(1, String.class, "unit", false, "UNIT");
        public final static Property Begindate = new Property(2, java.util.Date.class, "begindate", false, "BEGINDATE");
        public final static Property ProductObjectId = new Property(3, String.class, "productObjectId", false, "PRODUCT_OBJECT_ID");
        public final static Property Count = new Property(4, Integer.class, "count", false, "COUNT");
        public final static Property Period = new Property(5, Integer.class, "period", false, "PERIOD");
        public final static Property ObjectId = new Property(6, String.class, "objectId", false, "OBJECT_ID");
        public final static Property CreatedAt = new Property(7, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(8, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    }


    public EmpPowerDao(DaoConfig config) {
        super(config);
    }
    
    public EmpPowerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EMP_POWER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UNIT\" TEXT," + // 1: unit
                "\"BEGINDATE\" INTEGER," + // 2: begindate
                "\"PRODUCT_OBJECT_ID\" TEXT," + // 3: productObjectId
                "\"COUNT\" INTEGER," + // 4: count
                "\"PERIOD\" INTEGER," + // 5: period
                "\"OBJECT_ID\" TEXT," + // 6: objectId
                "\"CREATED_AT\" INTEGER," + // 7: createdAt
                "\"UPDATED_AT\" INTEGER);"); // 8: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EMP_POWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EmpPower entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(2, unit);
        }
 
        java.util.Date begindate = entity.getBegindate();
        if (begindate != null) {
            stmt.bindLong(3, begindate.getTime());
        }
 
        String productObjectId = entity.getProductObjectId();
        if (productObjectId != null) {
            stmt.bindString(4, productObjectId);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
 
        Integer period = entity.getPeriod();
        if (period != null) {
            stmt.bindLong(6, period);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(7, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(8, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(9, updatedAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EmpPower entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(2, unit);
        }
 
        java.util.Date begindate = entity.getBegindate();
        if (begindate != null) {
            stmt.bindLong(3, begindate.getTime());
        }
 
        String productObjectId = entity.getProductObjectId();
        if (productObjectId != null) {
            stmt.bindString(4, productObjectId);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
 
        Integer period = entity.getPeriod();
        if (period != null) {
            stmt.bindLong(6, period);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(7, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(8, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(9, updatedAt.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EmpPower readEntity(Cursor cursor, int offset) {
        EmpPower entity = new EmpPower( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // unit
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // begindate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // productObjectId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // count
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // period
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // objectId
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // createdAt
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EmpPower entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUnit(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBegindate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setProductObjectId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCount(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setPeriod(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setObjectId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreatedAt(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setUpdatedAt(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EmpPower entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EmpPower entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EmpPower entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
