package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PASSAGE".
*/
public class PassageDao extends AbstractDao<Passage, String> {

    public static final String TABLENAME = "PASSAGE";

    /**
     * Properties of entity Passage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Flag = new Property(0, String.class, "flag", false, "FLAG");
        public final static Property IsDel = new Property(1, Boolean.class, "isDel", false, "IS_DEL");
        public final static Property Capacity = new Property(2, Integer.class, "capacity", false, "CAPACITY");
        public final static Property Product = new Property(3, String.class, "product", false, "PRODUCT");
        public final static Property SeqNo = new Property(4, String.class, "seqNo", false, "SEQ_NO");
        public final static Property BorrowState = new Property(5, Boolean.class, "borrowState", false, "BORROW_STATE");
        public final static Property Stock = new Property(6, Integer.class, "stock", false, "STOCK");
        public final static Property WhorlSize = new Property(7, Integer.class, "whorlSize", false, "WHORL_SIZE");
        public final static Property IsSend = new Property(8, Boolean.class, "isSend", false, "IS_SEND");
        public final static Property ObjectId = new Property(9, String.class, "objectId", true, "OBJECT_ID");
        public final static Property CreatedAt = new Property(10, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(11, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    }


    public PassageDao(DaoConfig config) {
        super(config);
    }
    
    public PassageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PASSAGE\" (" + //
                "\"FLAG\" TEXT," + // 0: flag
                "\"IS_DEL\" INTEGER," + // 1: isDel
                "\"CAPACITY\" INTEGER," + // 2: capacity
                "\"PRODUCT\" TEXT," + // 3: product
                "\"SEQ_NO\" TEXT," + // 4: seqNo
                "\"BORROW_STATE\" INTEGER," + // 5: borrowState
                "\"STOCK\" INTEGER," + // 6: stock
                "\"WHORL_SIZE\" INTEGER," + // 7: whorlSize
                "\"IS_SEND\" INTEGER," + // 8: isSend
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 9: objectId
                "\"CREATED_AT\" INTEGER," + // 10: createdAt
                "\"UPDATED_AT\" INTEGER);"); // 11: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PASSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Passage entity) {
        stmt.clearBindings();
 
        String flag = entity.getFlag();
        if (flag != null) {
            stmt.bindString(1, flag);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        Integer capacity = entity.getCapacity();
        if (capacity != null) {
            stmt.bindLong(3, capacity);
        }
 
        String product = entity.getProduct();
        if (product != null) {
            stmt.bindString(4, product);
        }
 
        String seqNo = entity.getSeqNo();
        if (seqNo != null) {
            stmt.bindString(5, seqNo);
        }
 
        Boolean borrowState = entity.getBorrowState();
        if (borrowState != null) {
            stmt.bindLong(6, borrowState ? 1L: 0L);
        }
 
        Integer stock = entity.getStock();
        if (stock != null) {
            stmt.bindLong(7, stock);
        }
 
        Integer whorlSize = entity.getWhorlSize();
        if (whorlSize != null) {
            stmt.bindLong(8, whorlSize);
        }
 
        Boolean isSend = entity.getIsSend();
        if (isSend != null) {
            stmt.bindLong(9, isSend ? 1L: 0L);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(10, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(11, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(12, updatedAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Passage entity) {
        stmt.clearBindings();
 
        String flag = entity.getFlag();
        if (flag != null) {
            stmt.bindString(1, flag);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        Integer capacity = entity.getCapacity();
        if (capacity != null) {
            stmt.bindLong(3, capacity);
        }
 
        String product = entity.getProduct();
        if (product != null) {
            stmt.bindString(4, product);
        }
 
        String seqNo = entity.getSeqNo();
        if (seqNo != null) {
            stmt.bindString(5, seqNo);
        }
 
        Boolean borrowState = entity.getBorrowState();
        if (borrowState != null) {
            stmt.bindLong(6, borrowState ? 1L: 0L);
        }
 
        Integer stock = entity.getStock();
        if (stock != null) {
            stmt.bindLong(7, stock);
        }
 
        Integer whorlSize = entity.getWhorlSize();
        if (whorlSize != null) {
            stmt.bindLong(8, whorlSize);
        }
 
        Boolean isSend = entity.getIsSend();
        if (isSend != null) {
            stmt.bindLong(9, isSend ? 1L: 0L);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(10, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(11, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(12, updatedAt.getTime());
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9);
    }    

    @Override
    public Passage readEntity(Cursor cursor, int offset) {
        Passage entity = new Passage( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // flag
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isDel
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // capacity
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // product
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // seqNo
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // borrowState
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // stock
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // whorlSize
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // isSend
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // objectId
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // createdAt
            cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Passage entity, int offset) {
        entity.setFlag(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setIsDel(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setCapacity(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setProduct(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSeqNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBorrowState(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setStock(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setWhorlSize(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setIsSend(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setObjectId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCreatedAt(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setUpdatedAt(cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Passage entity, long rowId) {
        return entity.getObjectId();
    }
    
    @Override
    public String getKey(Passage entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Passage entity) {
        return entity.getObjectId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
