package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PASSAGE".
 */
@Entity
public class Passage {

    @Id
    private Long id;
    private Integer capacity;
    private String productObjectId;
    private String seqNo;
    private Boolean borrowState;
    private Integer stock;
    private Integer whorlSize;
    private Boolean isSend;
    private String objectId;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    @Generated
    public Passage() {
    }

    public Passage(Long id) {
        this.id = id;
    }

    @Generated
    public Passage(Long id, Integer capacity, String productObjectId, String seqNo, Boolean borrowState, Integer stock, Integer whorlSize, Boolean isSend, String objectId, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.capacity = capacity;
        this.productObjectId = productObjectId;
        this.seqNo = seqNo;
        this.borrowState = borrowState;
        this.stock = stock;
        this.whorlSize = whorlSize;
        this.isSend = isSend;
        this.objectId = objectId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    public String getProductObjectId() {
        return productObjectId;
    }

    public void setProductObjectId(String productObjectId) {
        this.productObjectId = productObjectId;
    }

    public String getSeqNo() {
        return seqNo;
    }

    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    public Boolean getBorrowState() {
        return borrowState;
    }

    public void setBorrowState(Boolean borrowState) {
        this.borrowState = borrowState;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Integer getWhorlSize() {
        return whorlSize;
    }

    public void setWhorlSize(Integer whorlSize) {
        this.whorlSize = whorlSize;
    }

    public Boolean getIsSend() {
        return isSend;
    }

    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
