package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PASSAGE".
*/
public class PassageDao extends AbstractDao<Passage, String> {

    public static final String TABLENAME = "PASSAGE";

    /**
     * Properties of entity Passage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Capacity = new Property(0, Integer.class, "capacity", false, "CAPACITY");
        public final static Property IsDel = new Property(1, Boolean.class, "isDel", false, "IS_DEL");
        public final static Property SeqNo = new Property(2, String.class, "seqNo", false, "SEQ_NO");
        public final static Property Used = new Property(3, String.class, "used", false, "USED");
        public final static Property Product = new Property(4, String.class, "product", false, "PRODUCT");
        public final static Property BorrowState = new Property(5, Boolean.class, "borrowState", false, "BORROW_STATE");
        public final static Property Stock = new Property(6, Integer.class, "stock", false, "STOCK");
        public final static Property IsSend = new Property(7, Boolean.class, "isSend", false, "IS_SEND");
        public final static Property Flag = new Property(8, String.class, "flag", false, "FLAG");
        public final static Property WhorlSize = new Property(9, Integer.class, "whorlSize", false, "WHORL_SIZE");
        public final static Property BorrowUser = new Property(10, String.class, "borrowUser", false, "BORROW_USER");
        public final static Property ObjectId = new Property(11, String.class, "objectId", true, "OBJECT_ID");
        public final static Property CreatedAt = new Property(12, String.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(13, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property Keepone = new Property(14, String.class, "keepone", false, "KEEPONE");
        public final static Property Keeptwo = new Property(15, String.class, "keeptwo", false, "KEEPTWO");
        public final static Property Keepthree = new Property(16, String.class, "keepthree", false, "KEEPTHREE");
    }


    public PassageDao(DaoConfig config) {
        super(config);
    }
    
    public PassageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PASSAGE\" (" + //
                "\"CAPACITY\" INTEGER," + // 0: capacity
                "\"IS_DEL\" INTEGER," + // 1: isDel
                "\"SEQ_NO\" TEXT," + // 2: seqNo
                "\"USED\" TEXT," + // 3: used
                "\"PRODUCT\" TEXT," + // 4: product
                "\"BORROW_STATE\" INTEGER," + // 5: borrowState
                "\"STOCK\" INTEGER," + // 6: stock
                "\"IS_SEND\" INTEGER," + // 7: isSend
                "\"FLAG\" TEXT," + // 8: flag
                "\"WHORL_SIZE\" INTEGER," + // 9: whorlSize
                "\"BORROW_USER\" TEXT," + // 10: borrowUser
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 11: objectId
                "\"CREATED_AT\" TEXT," + // 12: createdAt
                "\"UPDATED_AT\" TEXT," + // 13: updatedAt
                "\"KEEPONE\" TEXT," + // 14: keepone
                "\"KEEPTWO\" TEXT," + // 15: keeptwo
                "\"KEEPTHREE\" TEXT);"); // 16: keepthree
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PASSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Passage entity) {
        stmt.clearBindings();
 
        Integer capacity = entity.getCapacity();
        if (capacity != null) {
            stmt.bindLong(1, capacity);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        String seqNo = entity.getSeqNo();
        if (seqNo != null) {
            stmt.bindString(3, seqNo);
        }
 
        String used = entity.getUsed();
        if (used != null) {
            stmt.bindString(4, used);
        }
 
        String product = entity.getProduct();
        if (product != null) {
            stmt.bindString(5, product);
        }
 
        Boolean borrowState = entity.getBorrowState();
        if (borrowState != null) {
            stmt.bindLong(6, borrowState ? 1L: 0L);
        }
 
        Integer stock = entity.getStock();
        if (stock != null) {
            stmt.bindLong(7, stock);
        }
 
        Boolean isSend = entity.getIsSend();
        if (isSend != null) {
            stmt.bindLong(8, isSend ? 1L: 0L);
        }
 
        String flag = entity.getFlag();
        if (flag != null) {
            stmt.bindString(9, flag);
        }
 
        Integer whorlSize = entity.getWhorlSize();
        if (whorlSize != null) {
            stmt.bindLong(10, whorlSize);
        }
 
        String borrowUser = entity.getBorrowUser();
        if (borrowUser != null) {
            stmt.bindString(11, borrowUser);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(12, objectId);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(13, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(14, updatedAt);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(15, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(16, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(17, keepthree);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Passage entity) {
        stmt.clearBindings();
 
        Integer capacity = entity.getCapacity();
        if (capacity != null) {
            stmt.bindLong(1, capacity);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        String seqNo = entity.getSeqNo();
        if (seqNo != null) {
            stmt.bindString(3, seqNo);
        }
 
        String used = entity.getUsed();
        if (used != null) {
            stmt.bindString(4, used);
        }
 
        String product = entity.getProduct();
        if (product != null) {
            stmt.bindString(5, product);
        }
 
        Boolean borrowState = entity.getBorrowState();
        if (borrowState != null) {
            stmt.bindLong(6, borrowState ? 1L: 0L);
        }
 
        Integer stock = entity.getStock();
        if (stock != null) {
            stmt.bindLong(7, stock);
        }
 
        Boolean isSend = entity.getIsSend();
        if (isSend != null) {
            stmt.bindLong(8, isSend ? 1L: 0L);
        }
 
        String flag = entity.getFlag();
        if (flag != null) {
            stmt.bindString(9, flag);
        }
 
        Integer whorlSize = entity.getWhorlSize();
        if (whorlSize != null) {
            stmt.bindLong(10, whorlSize);
        }
 
        String borrowUser = entity.getBorrowUser();
        if (borrowUser != null) {
            stmt.bindString(11, borrowUser);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(12, objectId);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(13, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(14, updatedAt);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(15, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(16, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(17, keepthree);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11);
    }    

    @Override
    public Passage readEntity(Cursor cursor, int offset) {
        Passage entity = new Passage( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // capacity
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isDel
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // seqNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // used
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // product
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // borrowState
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // stock
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isSend
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // flag
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // whorlSize
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // borrowUser
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // objectId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // createdAt
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // updatedAt
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // keepone
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // keeptwo
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16) // keepthree
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Passage entity, int offset) {
        entity.setCapacity(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setIsDel(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setSeqNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUsed(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setProduct(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBorrowState(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setStock(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setIsSend(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setFlag(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWhorlSize(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setBorrowUser(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setObjectId(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCreatedAt(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setUpdatedAt(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setKeepone(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setKeeptwo(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setKeepthree(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Passage entity, long rowId) {
        return entity.getObjectId();
    }
    
    @Override
    public String getKey(Passage entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Passage entity) {
        return entity.getObjectId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
