package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.*;
import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRODUCT".
 */
@Entity
public class Product implements Serializable {
    private Boolean isDel;
    private String productName;
    private String cusProductName;

    @Id
    private String objectId;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String keepone;
    private String keeptwo;
    private String keepthree;

    @Generated
    public Product() {
    }

    public Product(String objectId) {
        this.objectId = objectId;
    }

    @Generated
    public Product(Boolean isDel, String productName, String cusProductName, String objectId, java.util.Date createdAt, java.util.Date updatedAt, String keepone, String keeptwo, String keepthree) {
        this.isDel = isDel;
        this.productName = productName;
        this.cusProductName = cusProductName;
        this.objectId = objectId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.keepone = keepone;
        this.keeptwo = keeptwo;
        this.keepthree = keepthree;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getCusProductName() {
        return cusProductName;
    }

    public void setCusProductName(String cusProductName) {
        this.cusProductName = cusProductName;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getKeepone() {
        return keepone;
    }

    public void setKeepone(String keepone) {
        this.keepone = keepone;
    }

    public String getKeeptwo() {
        return keeptwo;
    }

    public void setKeeptwo(String keeptwo) {
        this.keeptwo = keeptwo;
    }

    public String getKeepthree() {
        return keepthree;
    }

    public void setKeepthree(String keepthree) {
        this.keepthree = keepthree;
    }

}
