package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT".
*/
public class ProductDao extends AbstractDao<Product, Long> {

    public static final String TABLENAME = "PRODUCT";

    /**
     * Properties of entity Product.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property CusProductName = new Property(2, String.class, "cusProductName", false, "CUS_PRODUCT_NAME");
        public final static Property CusProductObjectId = new Property(3, String.class, "cusProductObjectId", false, "CUS_PRODUCT_OBJECT_ID");
        public final static Property CusProductCreateAt = new Property(4, java.util.Date.class, "cusProductCreateAt", false, "CUS_PRODUCT_CREATE_AT");
        public final static Property CusProductUpdateAt = new Property(5, java.util.Date.class, "cusProductUpdateAt", false, "CUS_PRODUCT_UPDATE_AT");
        public final static Property ObjectId = new Property(6, String.class, "objectId", false, "OBJECT_ID");
        public final static Property CreatedAt = new Property(7, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(8, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    }


    public ProductDao(DaoConfig config) {
        super(config);
    }
    
    public ProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"CUS_PRODUCT_NAME\" TEXT," + // 2: cusProductName
                "\"CUS_PRODUCT_OBJECT_ID\" TEXT," + // 3: cusProductObjectId
                "\"CUS_PRODUCT_CREATE_AT\" INTEGER," + // 4: cusProductCreateAt
                "\"CUS_PRODUCT_UPDATE_AT\" INTEGER," + // 5: cusProductUpdateAt
                "\"OBJECT_ID\" TEXT," + // 6: objectId
                "\"CREATED_AT\" INTEGER," + // 7: createdAt
                "\"UPDATED_AT\" INTEGER);"); // 8: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Product entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String cusProductName = entity.getCusProductName();
        if (cusProductName != null) {
            stmt.bindString(3, cusProductName);
        }
 
        String cusProductObjectId = entity.getCusProductObjectId();
        if (cusProductObjectId != null) {
            stmt.bindString(4, cusProductObjectId);
        }
 
        java.util.Date cusProductCreateAt = entity.getCusProductCreateAt();
        if (cusProductCreateAt != null) {
            stmt.bindLong(5, cusProductCreateAt.getTime());
        }
 
        java.util.Date cusProductUpdateAt = entity.getCusProductUpdateAt();
        if (cusProductUpdateAt != null) {
            stmt.bindLong(6, cusProductUpdateAt.getTime());
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(7, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(8, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(9, updatedAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Product entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String cusProductName = entity.getCusProductName();
        if (cusProductName != null) {
            stmt.bindString(3, cusProductName);
        }
 
        String cusProductObjectId = entity.getCusProductObjectId();
        if (cusProductObjectId != null) {
            stmt.bindString(4, cusProductObjectId);
        }
 
        java.util.Date cusProductCreateAt = entity.getCusProductCreateAt();
        if (cusProductCreateAt != null) {
            stmt.bindLong(5, cusProductCreateAt.getTime());
        }
 
        java.util.Date cusProductUpdateAt = entity.getCusProductUpdateAt();
        if (cusProductUpdateAt != null) {
            stmt.bindLong(6, cusProductUpdateAt.getTime());
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(7, objectId);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(8, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(9, updatedAt.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Product readEntity(Cursor cursor, int offset) {
        Product entity = new Product( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cusProductName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cusProductObjectId
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // cusProductCreateAt
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // cusProductUpdateAt
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // objectId
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // createdAt
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Product entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCusProductName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCusProductObjectId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCusProductCreateAt(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setCusProductUpdateAt(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setObjectId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreatedAt(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setUpdatedAt(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Product entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Product entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Product entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
