package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUPPLY_RECORD".
*/
public class SupplyRecordDao extends AbstractDao<SupplyRecord, Long> {

    public static final String TABLENAME = "SUPPLY_RECORD";

    /**
     * Properties of entity SupplyRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsFlag = new Property(1, Boolean.class, "isFlag", false, "IS_FLAG");
        public final static Property Passage = new Property(2, String.class, "passage", false, "PASSAGE");
        public final static Property Card = new Property(3, String.class, "card", false, "CARD");
        public final static Property Count = new Property(4, Integer.class, "count", false, "COUNT");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Keepone = new Property(6, String.class, "keepone", false, "KEEPONE");
        public final static Property Keeptwo = new Property(7, String.class, "keeptwo", false, "KEEPTWO");
        public final static Property Keepthree = new Property(8, String.class, "keepthree", false, "KEEPTHREE");
    }


    public SupplyRecordDao(DaoConfig config) {
        super(config);
    }
    
    public SupplyRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUPPLY_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IS_FLAG\" INTEGER," + // 1: isFlag
                "\"PASSAGE\" TEXT," + // 2: passage
                "\"CARD\" TEXT," + // 3: card
                "\"COUNT\" INTEGER," + // 4: count
                "\"TIME\" TEXT," + // 5: time
                "\"KEEPONE\" TEXT," + // 6: keepone
                "\"KEEPTWO\" TEXT," + // 7: keeptwo
                "\"KEEPTHREE\" TEXT);"); // 8: keepthree
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUPPLY_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SupplyRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isFlag = entity.getIsFlag();
        if (isFlag != null) {
            stmt.bindLong(2, isFlag ? 1L: 0L);
        }
 
        String passage = entity.getPassage();
        if (passage != null) {
            stmt.bindString(3, passage);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(7, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(8, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(9, keepthree);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SupplyRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isFlag = entity.getIsFlag();
        if (isFlag != null) {
            stmt.bindLong(2, isFlag ? 1L: 0L);
        }
 
        String passage = entity.getPassage();
        if (passage != null) {
            stmt.bindString(3, passage);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(7, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(8, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(9, keepthree);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SupplyRecord readEntity(Cursor cursor, int offset) {
        SupplyRecord entity = new SupplyRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isFlag
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // passage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // card
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // count
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // keepone
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // keeptwo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // keepthree
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SupplyRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsFlag(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setPassage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCard(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCount(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setKeepone(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setKeeptwo(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setKeepthree(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SupplyRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SupplyRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SupplyRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
