package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SUPPLY_RECORD".
 */
@Entity
public class SupplyRecord {

    @Id
    private Long id;
    private Boolean isFlag;
    private String passage;
    private String card;
    private Integer count;
    private String time;

    @Generated
    public SupplyRecord() {
    }

    public SupplyRecord(Long id) {
        this.id = id;
    }

    @Generated
    public SupplyRecord(Long id, Boolean isFlag, String passage, String card, Integer count, String time) {
        this.id = id;
        this.isFlag = isFlag;
        this.passage = passage;
        this.card = card;
        this.count = count;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsFlag() {
        return isFlag;
    }

    public void setIsFlag(Boolean isFlag) {
        this.isFlag = isFlag;
    }

    public String getPassage() {
        return passage;
    }

    public void setPassage(String passage) {
        this.passage = passage;
    }

    public String getCard() {
        return card;
    }

    public void setCard(String card) {
        this.card = card;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
