package com.seekersoftvendingapp.database.table;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAKEOUT_RECORD".
 */
@Entity
public class TakeoutRecord {

    @Id
    private Long id;
    private Boolean isFlag;
    private String passaga;
    private String card;
    private String time;

    @Generated
    public TakeoutRecord() {
    }

    public TakeoutRecord(Long id) {
        this.id = id;
    }

    @Generated
    public TakeoutRecord(Long id, Boolean isFlag, String passaga, String card, String time) {
        this.id = id;
        this.isFlag = isFlag;
        this.passaga = passaga;
        this.card = card;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsFlag() {
        return isFlag;
    }

    public void setIsFlag(Boolean isFlag) {
        this.isFlag = isFlag;
    }

    public String getPassaga() {
        return passaga;
    }

    public void setPassaga(String passaga) {
        this.passaga = passaga;
    }

    public String getCard() {
        return card;
    }

    public void setCard(String card) {
        this.card = card;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
