package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAKEOUT_RECORD".
*/
public class TakeoutRecordDao extends AbstractDao<TakeoutRecord, Long> {

    public static final String TABLENAME = "TAKEOUT_RECORD";

    /**
     * Properties of entity TakeoutRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsFlag = new Property(1, Boolean.class, "isFlag", false, "IS_FLAG");
        public final static Property Passaga = new Property(2, String.class, "passaga", false, "PASSAGA");
        public final static Property Card = new Property(3, String.class, "card", false, "CARD");
        public final static Property Time = new Property(4, String.class, "time", false, "TIME");
    }


    public TakeoutRecordDao(DaoConfig config) {
        super(config);
    }
    
    public TakeoutRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAKEOUT_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IS_FLAG\" INTEGER," + // 1: isFlag
                "\"PASSAGA\" TEXT," + // 2: passaga
                "\"CARD\" TEXT," + // 3: card
                "\"TIME\" TEXT);"); // 4: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAKEOUT_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TakeoutRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isFlag = entity.getIsFlag();
        if (isFlag != null) {
            stmt.bindLong(2, isFlag ? 1L: 0L);
        }
 
        String passaga = entity.getPassaga();
        if (passaga != null) {
            stmt.bindString(3, passaga);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TakeoutRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isFlag = entity.getIsFlag();
        if (isFlag != null) {
            stmt.bindLong(2, isFlag ? 1L: 0L);
        }
 
        String passaga = entity.getPassaga();
        if (passaga != null) {
            stmt.bindString(3, passaga);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TakeoutRecord readEntity(Cursor cursor, int offset) {
        TakeoutRecord entity = new TakeoutRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isFlag
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // passaga
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // card
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TakeoutRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsFlag(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setPassaga(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCard(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TakeoutRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TakeoutRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TakeoutRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
