package com.seekersoftvendingapp.database.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAKEOUT_RECORD".
*/
public class TakeoutRecordDao extends AbstractDao<TakeoutRecord, Long> {

    public static final String TABLENAME = "TAKEOUT_RECORD";

    /**
     * Properties of entity TakeoutRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsDel = new Property(1, Boolean.class, "isDel", false, "IS_DEL");
        public final static Property Passage = new Property(2, String.class, "passage", false, "PASSAGE");
        public final static Property Card = new Property(3, String.class, "card", false, "CARD");
        public final static Property ProductId = new Property(4, String.class, "productId", false, "PRODUCT_ID");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Count = new Property(6, Integer.class, "count", false, "COUNT");
        public final static Property Keepone = new Property(7, String.class, "keepone", false, "KEEPONE");
        public final static Property Keeptwo = new Property(8, String.class, "keeptwo", false, "KEEPTWO");
        public final static Property Keepthree = new Property(9, String.class, "keepthree", false, "KEEPTHREE");
    }


    public TakeoutRecordDao(DaoConfig config) {
        super(config);
    }
    
    public TakeoutRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAKEOUT_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IS_DEL\" INTEGER," + // 1: isDel
                "\"PASSAGE\" TEXT," + // 2: passage
                "\"CARD\" TEXT," + // 3: card
                "\"PRODUCT_ID\" TEXT," + // 4: productId
                "\"TIME\" TEXT," + // 5: time
                "\"COUNT\" INTEGER," + // 6: count
                "\"KEEPONE\" TEXT," + // 7: keepone
                "\"KEEPTWO\" TEXT," + // 8: keeptwo
                "\"KEEPTHREE\" TEXT);"); // 9: keepthree
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAKEOUT_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TakeoutRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        String passage = entity.getPassage();
        if (passage != null) {
            stmt.bindString(3, passage);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        String productId = entity.getProductId();
        if (productId != null) {
            stmt.bindString(5, productId);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(7, count);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(8, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(9, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(10, keepthree);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TakeoutRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(2, isDel ? 1L: 0L);
        }
 
        String passage = entity.getPassage();
        if (passage != null) {
            stmt.bindString(3, passage);
        }
 
        String card = entity.getCard();
        if (card != null) {
            stmt.bindString(4, card);
        }
 
        String productId = entity.getProductId();
        if (productId != null) {
            stmt.bindString(5, productId);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(7, count);
        }
 
        String keepone = entity.getKeepone();
        if (keepone != null) {
            stmt.bindString(8, keepone);
        }
 
        String keeptwo = entity.getKeeptwo();
        if (keeptwo != null) {
            stmt.bindString(9, keeptwo);
        }
 
        String keepthree = entity.getKeepthree();
        if (keepthree != null) {
            stmt.bindString(10, keepthree);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TakeoutRecord readEntity(Cursor cursor, int offset) {
        TakeoutRecord entity = new TakeoutRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isDel
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // passage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // card
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // productId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // count
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // keepone
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // keeptwo
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // keepthree
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TakeoutRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsDel(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setPassage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCard(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setProductId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setKeepone(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setKeeptwo(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setKeepthree(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TakeoutRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TakeoutRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TakeoutRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
