/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seekersoftvendingapp_serialport_SeekerSoftSerialPort */

#ifndef _Included_com_seekersoftvendingapp_serialport_SeekerSoftSerialPort
#define _Included_com_seekersoftvendingapp_serialport_SeekerSoftSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seekersoftvendingapp_serialport_SeekerSoftSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_seekersoftvendingapp_serialport_SeekerSoftSerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_seekersoftvendingapp_serialport_SeekerSoftSerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seekersoftvendingapp_serialport_SeekerSoftSerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
